### ISSUE TITLE
심화주차 과제 피드백 - 강동영 튜터

### ISSUE THREAD

**Issue by kangddong** [gahyejeon/pokeBook#1]
# 좋은점
- `DispatchGroup` 도입해보려고 공부해서 사용하신 점, API는 바르게 잘 사용하셨습니다.
- 주어진 기간에 과제를 전부 완성한점은 잘하셨습니다.

# 아쉬운점
- 아직 RxSwift와 MVVM이 이해가 될듯, 말듯하신 것 같습니다 !

## Model의 부재
Model layer가 없습니다
현재 사용되는 `Pokemon.swift `파일에는 네트워크 통신시 json 데이터를 **디코딩하는 DTO**의 역할을 하고있습니다.

그렇다면 비즈니스로직을 어디서 처리 하는가를 보게되면 `viewmodel`에서 하게됩니다.
`model` 에서 포켓몬API 를 호출 후 viewmodel에서 해당 데이터를 가공 및 전달을 해주면 역할이 분리가 될 것 같습니다.

## DetailViewModel 로직
`DispatchGroup` 을 사용하신 점은 좋았지만, `MainViewController`에서, `DetailViewController`의 API까지 요청하신 부분은 분리하는게 좋습니다. **유즈케이스를 고려**해보면 `MainViewController` 에서 `DetailViewController`로 이동할 수도, 이동하지 않을 수도 있습니다.
API 는 앱이 아닌 외부 서버에 요청하기 때문에, 값이 변할 가능성도 있기에 `DetailViewController` 에 대한 정보는 `DetailViewController` 진입할 시에 요청하는게 좋습니다.

# 학습방향성

## MVVM & RxSwift
현재 전반적으로 주어진 문제를 이해하는것은 큰 어려움은 없어보입니다만, 다소 러닝커브가 높은 MVVM과 RxSwift를 학습하면서 이해가 될듯 말듯 하신것 같아요
1. DTO에 대해서 학습한 후, Model과 DTO의 차이를 이해하시면 좋을 것 같습니다.
2. RxSwift의 공식문서는 한국어를 지원합니다 ! **개요와 Observable**  를 읽어보면서 모르는 개발용어(영어 사전적인 의미X) 를 먼저 정리해보시고, 간략하게 학습 및 튜터님들에게 질문하셔서 배경지식을 쌓아가면서 반복적으로 읽어보시면 금새 이해되실거에요

## git 관련
1. 팀 협업에서 사용했던 커밋 컨벤션을 그대로 개인 플젝에서 습관을 들이는 것을 추천드립니다 ! 
2. 급해서 커밋을 못하게됐다고 하셨는데, 모든 사고(프로젝트가 날라간다던지,,)는 평소와 다른 예외적인 상황에서 유독 일어납니다. 앞으로는 급할 수록 커밋을 하자고 생각을 바꿔보시면 좋을거같아요 !

## gpt 관련
인공지능과 함께 학습하셨다고 솔직하게 말씀해주셔서 오히려 감사합니다 ! 
현업에서도 gpt를 사용하기에 사용하는 것에 대해서 전혀 부정적으로 보실 필요는 없는 것 같아요
**다만 활용하는 법에 있어서, 답을 요구하기보다 과정 혹은 개념을 정리해달라고하는 방식을 사용해보는 것은 어떨까요 ?**

예를 들어 level1 `func fetch<T: Decodable>(url: URL) -> Single<T>` 과 같은 메서드를 제공했을 때
Generic 문법과 RxSwift, 그리고 Single에 대한 이해가 있어야합니다.
학습에 어려움을 겪는 많은 분들의 공통점은 기억에 의존합니다. 우리 기억은 ram 메모리와 같기에 휘발성이 있습니다.
숙달하기 위해서는 반복을 해야합니다. 그렇기에 기억에 의존하기 보다, 내배캠에 잘 정리되어 있는 자료와 공식문서를 먼저 보시고, 본인 나름의 정리를 한 후에 gpt와 같이 공부하면 그 또한 효율적으로 다가올거에요
극단적으로는, level 2~3까지만 개발하더라도 gpt를 사용하지않기로 약속하고 가혜님과 튜터님들의 도움만으로 공부해보시는 것도 추천드립니다.

좋은 습관 형성이 자연스럽게 실력향상을 도와줄거에요 ! 습관은 하루아침에 생기지않아서 괴롭지만,
개발을 척척하고있는 가혜님의 모습을 상상해보시면 어떨까요 ?
괴롭고 힘든 마음보다, 긍정적이고 밝은 미래를 기다리면서 공부하시는 가혜님이 더 멋진 개발자가 될 것이라고 생각합니다.

**Comment by gahyejeon** [comment]
동영튜터님 자세한 피드백 너무 감사합니다. 튜터님의 피드백으로 인해 제 과제에 대한 공부를 어떻게 다시 해봐야할지 감이 잡히는것 같습니다. 다시 제 코드를 보면서 튜터님의 피드백을 반영하여 공부해보겠습니다 감사합니다
